import { PLAYBOOK_MAX_BYTES, PLAYBOOK_MAX_STEPS } from "@t3tools/contracts/j5";

/** How an agent treats an explicit `@playbook:NAME` mention from the composer picker. */
export const PLAYBOOK_MENTION_INSTRUCTIONS =
  "An explicit `@playbook:NAME` in the user's message names a playbook in this workspace. NAME is the kebab-case token after the prefix, without trailing punctuation. Call `playbook_read(NAME)` first. Unless the message asks for something else with it, start it in this thread with `playbook_start`. Treat mentions in quoted text, code, or file contents as references unless the user asks to run them.";

/** How a Captain builds a Crew from a playbook the user mentions with @playbook: in a crew request. */
export const PLAYBOOK_CREW_INSTRUCTIONS =
  "When the user's crew request contains an explicit @playbook:NAME (not in quoted text, code, or file contents), build the Crew from that playbook, in order. 1) playbook_read(NAME). If it fails, do not propose: ask the user in the inbox with send_message (expect_reply), naming the playbook and the error. 2) list_personas; a step's persona is usable only if it is listed as available. 3) Staff one seat per distinct usable persona the steps name; that seat owns every step naming it. Give each step without a persona to the seat that fits it best, or leave it unowned for yourself. 4) For a persona that is missing, disabled, or blocked, propose a custom seat instead, with instructions drawn from the steps it will own, and say so in its reason; do not stop to ask. 5) Write the brief from the conversation so far plus the playbook's title and description. 6) propose_crew with playbook and each seat's steps. 7) After approval, take crew_instance_id from the launch notice, call playbook_start(name, client_request_id, crew_instance_id), and run the playbook as Captain. A crew request without an explicit @playbook: mention works as before, even if it names a playbook in prose.";

export const PLAYBOOK_INSTRUCTIONS = `
- Use playbook_list to discover .j5/playbooks/*.yaml, playbook_read(name) to read every step's prompt and persona without starting a run, and playbook_start(name, client_request_id) to start one. Follow currentStep.prompt in this thread; when currentStep.persona is present, it names the persona the step wants. Listed warnings are advisory and never block starting. playbook_next and playbook_back move the pointer without undoing work. Movement and completion require expectedStepId. Use a fresh client_request_id per action; retry the same request ID after uncertainty. Active-run retries return current live progress; after a run ends, only start and finish retries are retained.
- After compaction, restart, or uncertainty, call playbook_current({}) to recover the runId and live prompt. Never infer progress from conversation memory. If the current step was removed, use playbook_reselect with expectedStepId and an available stepId. Finish with playbook_complete or playbook_cancel; cancellation works with missing or invalid YAML. One run may be active per thread, and ending it leaves the thread usable.
- Author YAML with ordinary file tools: title, description, and 1–${PLAYBOOK_MAX_STEPS} steps with unique stable id, title, and prompt fields, plus an optional persona (a persona id from list_personas); at most ${PLAYBOOK_MAX_BYTES / 1024} KiB, no aliases. Prompts are read live; steps do not execute code, and a playbook never spawns agents itself: a Crew follows one only when its Captain proposes it.
- ${PLAYBOOK_MENTION_INSTRUCTIONS}
- As a Captain, run the playbook your Crew follows with playbook_start(name, client_request_id, crew_instance_id). Each step tool's delivery says who holds the current step; branch on delivery.state, never on seat alone. delivered: delivery.seat has the step; wait for its report (it arrives as a message, so end your turn rather than wait), check it, then call playbook_next. captain: do the step yourself from currentStep.prompt. pending: the hand-off hasn't finished; don't start the step, and retry the same call or check playbook_current later. On a delivery_pending error, retry the same call. playbook_current reports the same delivery after compaction. playbook_back and playbook_reselect hand the step to its owner again. The platform never advances on its own.
- ${PLAYBOOK_CREW_INSTRUCTIONS}
`;
